# Generated by Django 5.2.5 on 2025-08-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(blank=True, default='Anonyme', max_length=100, null=True),
        ),
    ]
